name: Check Xcode Version

on:
  push:
    branches:
      - main

jobs:
  check-xcode-version:
    runs-on: macOS-latest

    steps:
      - name: Check Xcode version
        run: |
          xcodebuild -version
