name: Build and Download App

on:
  push:
    branches:
      - main

jobs:
  build-and-download:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          xcodebuild clean build -project DemoCiCd.xcodeproj -scheme DemoCiCd -destination 'platform=iOS Simulator,name=iPhone 12'

      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: DemoCiCd
          path: build/Release-iphonesimulator/DemoCiCd.app
